### ISSUE TITLE
optimal li instruction

### ISSUE THREAD

**Issue by enthusi** [theandrew168/bronzebeard#11]
li	a4,4
gets assembled into
lui      x14,0x0    
addi     x14, x14, 4
instead of
addi x14, zero,4

So it should check for signed 12bit range and omit the lui if not required.

**Comment by theandrew168** [comment]
Notes from our recent discussion of this issue:
```
Currently, the assembler doesn't support passes that would alter label locations.
Examples of this would be the LI, CALL, and TAIL pseudo-insts (grow) or compressed inst swaps (shrink).

There is currently a chicken and the egg problem:
labels depend on inst sizes
immediates depend on labels
inst sizes depend on immediates

labels -> sizes
imms   -> labels
sizes  -> imms

How can this be avoided?
How do traditional assemblers / linkers solve this?
```

**Comment by theandrew168** [comment]
Just finished up my first crack at this tonight. Go ahead and give `LI` another try. I've still got a bit more to do on `CALL`, `TAIL`, and the compressed instructions. But overall, I think I found a design change that's going to work!

**Comment by enthusi** [comment]
great job on li !
without a single change in the source file:
2072 Bytes
vs
1856 Bytes

there is still one thing missed, this time 'the other way round'
li t3, 16384 becomes:
67c: 00004e37 lui x28 0x4
680: 000e0e13 addi x28 x28 0

so a redundant add of 0.
I have a few of such cases. But that looks like a reasonably simply fix fortunately.

**Comment by theandrew168** [comment]
Good call! I've got this implemented now, too. Go ahead and see if everything looks correct on your end.
