### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by NickHerrig** [theandrew168/bronzebeard#15]
I came across an interesting package called (tqdm)[https://github.com/noamraph/tqdm] whilst reading fluent python and thought it might be a solid addition to the assembler when compiling larger programs. 

Let me know what you think, and if Interested I can get a PR going.

**Comment by theandrew168** [comment]
I love TQDM! I actually just used it a few weeks back on my [nn-from-scratch](https://github.com/theandrew168/nn-from-scratch) repo. I really love it but the assembler is quick enough that I doubt anyone would ever get to see it shine! I think that if the programs devs write with Bronzebeard end up taking more time, TQDM may be a good addition.

**Comment by NickHerrig** [comment]
That's a really good point, as of right now, it'd add more complexity really for no gain! 
Place it on the back burner or potential nice to haves when we are writing large bare metal riscv web servers that take a longer time to assemble!
