### ISSUE TITLE
Is there any way to output .hex format instead of bb.out

### ISSUE THREAD

**Issue by sahasradal** [theandrew168/bronzebeard#20]
Hi sir,
I am using windows OS. I installed bronzebeard and it assembles properly the Longan nano example and outputs a bb.out file . I tried to install zadig but the longan nano cannot be programmed from windows. Later I tried with a VM ubuntu installation and the programming was successful. Is it possible that bronzebeard can output a .HEX format file so that it can be uploaded by the programming software provided by sipeed. The sipeed program software accepts .hex and .bin as inputs. bb.out is not recognized.
I am a novice (hobbyist) and started studying RISCV and have no exposure to any other language than AVR assembly . If bronzebeard can output these formats then it would be easy to program from windows10 with sipeed software (GD32 MCU dfu tool_v3.8.1.5784)without the hassle of running a linuxVM which is very cubersome with 20gb space lost. It would be so kind of you if this option can be enabled.
Regards
Sajeev

**Comment by theandrew168** [comment]
Hey Sajeev,

i just finished adding a CLI flag to output an additional file in the Intel HEX format. You must provide an offset for where the HEX file should be written to the device's ROM. The output file will be named whatever name was provided for `-o / --output` with an additional `.hex` extension.

Longan Nano example:
```
bronzebeard --hex-offset 0x08000000 examples/longan_nano_led.asm
```

You'll need to update to the latest version of bronzebeard to see this flag (0.1.17). Let me know if this works for you!

**Comment by sahasradal** [comment]
Dear Sir,
Thank you very much for creating the Intel HEX output option to BRONZEBEARD. I tried as you instructed and worked like a charm. A file named bb (OUT format) and another file with bb,out (IntelHEX) format was output in my base directory. I used the Longan Nano DFU tool   "GD32 Dfu Tool_V3.8.2.9056" which  recognized the .HEX file to program the chip in DFU mode. The tool is available for download at GIGAdevices website.
1) in windows command prompt  create virtual environment by typing -   python3 -m venv tutorial-env
2) activated the virtual environment with command  -  tutorial-env\Scripts\activate.bat
3) downloaded latest bronzebeard 0.01.17 by typing  - pip install bronzebeard
3) Placed mandlebrot.asm & gd32vf103.asm(include) files on desktop
4) typed bronzebeard command -         bronzebeard --hex-offset 0x08000000 Desktop/mandelbrot.asm
5) found the bb. OUT file and bb.out. HEX file in the command prompt folder
6) Cycle the boot button and reset button of Longan nano to enter DFU mode
7) Used the  "GD32 Dfu Tool_V3.8.2.9056" tool to navigate to the command prompt folder , select bb.out.HEX  and burn chip.
9) The Mandelbrot displayed on the LCD.
Happy programming RISCV assembly with BRONZEBEARD on windows10
DFU tool available on https://www.gd32mcu.com/en/download/7?kw=GD32VF1


A thousand thanks for this tool 

Regards
Sajeev

![install bronzebeard](https://user-images.githubusercontent.com/36818909/178148929-64a3f50a-1f8f-4fbf-85cd-f882ff26a551.jpg)

**Comment by sahasradal** [comment]
![image](https://user-images.githubusercontent.com/36818909/178149017-95b7408c-9806-4e04-b4d6-4d7d06a87b45.png)

**Comment by sahasradal** [comment]
Dear Sir,
Please dont feel that this person is too intrusive. If you can modify the readme with some basic example commands showing how to use the keywords of this assembler such as verbose,output, compress, offset etc etc , it would be very useful how to use this assembler to its full strength. People like me with little knowledge will benefit from such mini user manual which will give idea on how to write a basic command for bronzebeard.
Regards
Sajeev

**Comment by theandrew168** [comment]
Hey there @sahasradal , sorry for the long delay. I've added a new issue (#22) to track updating the documentation with more details on how to use the CLI.
