### ISSUE TITLE
CSR privilaged instructions

### ISSUE THREAD

**Issue by sahasradal** [theandrew168/bronzebeard#21]
Dear Sir,
Is there a possibility of adding CSR privileged instructions to Bronzebeard such as CSRRW, CSRRS, and CSRRC without which interrupt enabling seems impossible.
Regards
Sajeev

**Comment by theandrew168** [comment]
"Zifencei" and "Zicsr" instructions have been added in version `0.2.0`!

**Comment by sahasradal** [comment]
Thankyou sirWith gratitudeSajeev

Sent from Yahoo Mail on Android 
 
  On Thu, 29 Dec 2022 at 1:37 am, Andrew ***@***.***> wrote:   


Closed #21 as completed.
