### ISSUE TITLE
A comment placed on the same line as an include directive gives an uninformative error

### ISSUE THREAD

**Issue by efficacy** [theandrew168/bronzebeard#25]
The processing for the include directive is performed before lexical analysis, and thus before comment removal, so any in-line comments on the same line as an include directive will be treated as part of the filename and cause a confusing error message.

In this special case, in-line comments need to be removed before the include directive is processed

**Comment by theandrew168** [comment]
Fixed by 47a5fceec66d5ee75ee6c212639b9b9cb864dc28. Thanks for pointing this out! Version 0.2.2 includes the fix.
